from fastapi import FastAPI, APIRouter, HTTPException, status
from fastapi.responses import FileResponse, StreamingResponse
from dotenv import load_dotenv
from starlette.middleware.cors import CORSMiddleware
from motor.motor_asyncio import AsyncIOMotorClient
import os
import logging
from pathlib import Path
from pydantic import BaseModel
from typing import List, Optional, Dict, Any
from datetime import datetime, timezone
from openai import OpenAI
import json
import subprocess
import tempfile
import zipfile
import io

ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / '.env')

mongo_url = os.environ['MONGO_URL']
client = AsyncIOMotorClient(mongo_url)
db = client[os.environ['DB_NAME']]

perplexity_client = OpenAI(
    api_key=os.environ.get('PERPLEXITY_API_KEY'),
    base_url="https://api.perplexity.ai"
)

kaggle_username = os.environ.get('KAGGLE_USERNAME')
kaggle_key = os.environ.get('KAGGLE_KEY')

app = FastAPI(title="Alexandria API")
api_router = APIRouter(prefix="/api")

# ============ MODELS ============

class Citation(BaseModel):
    title: str
    url: str

class StepRequest(BaseModel):
    session_id: str
    topic: str
    step: int
    selected_data: Optional[Dict[str, Any]] = None

class StepResponse(BaseModel):
    step: int
    content: str
    citations: List[Citation] = []
    options: Optional[List[Dict[str, Any]]] = None
    next_step_available: bool = False

class NotebookRequest(BaseModel):
    session_id: str
    topic: str
    dataset_name: str

# ============ HELPERS ============

def extract_citations(response) -> List[Citation]:
    citations = []
    if hasattr(response, 'citations') and response.citations:
        for i, url in enumerate(response.citations):
            citations.append(Citation(title=f"[{i+1}]", url=url))
    return citations

def run_kaggle_command(command: List[str]) -> str:
    kaggle_config = {"username": kaggle_username, "key": kaggle_key}
    with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
        json.dump(kaggle_config, f)
        temp_file = f.name
    
    try:
        env = os.environ.copy()
        env['KAGGLE_USERNAME'] = kaggle_username
        env['KAGGLE_KEY'] = kaggle_key
        # Add venv bin to PATH to find kaggle command
        if '/root/.venv/bin' not in env.get('PATH', ''):
            env['PATH'] = f"/root/.venv/bin:{env.get('PATH', '')}"
        result = subprocess.run(command, capture_output=True, text=True, env=env, timeout=30)
        return result.stdout
    finally:
        if os.path.exists(temp_file):
            os.remove(temp_file)

async def generate_notebook_from_research(session_id: str, topic: str, dataset: str) -> dict:
    """Generate notebook with ALL research data from conversation"""
    
    # Fetch ALL research data from MongoDB
    research_doc = await db.research.find_one({"session_id": session_id, "step": 1})
    
    if not research_doc:
        # Fallback to generic if no data
        logging.warning(f"No research data found for session {session_id}, using template")
        research_content = f"# Research on {topic}\n\nThis is a template notebook. Complete the research flow in Alexandria to generate a notebook with your actual research data."
        gaps_content = "No gaps analysis available yet."
        dataset_content = f"Dataset: {dataset}"
        implementation_content = "Complete the implementation plan in Alexandria."
    else:
        research_content = research_doc.get('content', 'No research content available')
        gaps_content = research_doc.get('gaps', 'No gaps identified yet')
        dataset_content = research_doc.get('datasets', 'No datasets found')
        implementation_content = research_doc.get('implementation', 'No implementation plan yet')
        logging.info(f"Loaded research data for session {session_id}: {len(research_content)} chars")
    
    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    f"# {topic}\n",
                    "\n",
                    f"**Dataset:** {dataset}\n",
                    "**Generated by:** Alexandria Research Assistant\n",
                    f"**Date:** {datetime.now().strftime('%Y-%m-%d')}\n",
                    "\n",
                    "---\n",
                    "\n",
                    "This notebook was automatically generated by Alexandria with comprehensive research data.\n"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 📚 Research Background & Literature Review\n",
                    "\n",
                    research_content if research_content else "No research data available"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 💡 Research Gaps & Opportunities\n",
                    "\n",
                    gaps_content if gaps_content else "No gaps analysis available"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 📊 Dataset Information\n",
                    "\n",
                    dataset_content if dataset_content else f"Dataset: {dataset}"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## ⚙️ Implementation Strategy\n",
                    "\n",
                    implementation_content if implementation_content else "No implementation plan available"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["## 1. Setup & Imports\n", "\n", "Install and import required libraries."]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import numpy as np\n",
                    "import pandas as pd\n",
                    "import matplotlib.pyplot as plt\n",
                    "import seaborn as sns\n",
                    "\n",
                    "import torch\n",
                    "import torch.nn as nn\n",
                    "from torch.utils.data import Dataset, DataLoader\n",
                    "import torchvision.transforms as transforms\n",
                    "\n",
                    "from sklearn.model_selection import train_test_split\n",
                    "from sklearn.metrics import accuracy_score, classification_report\n",
                    "\n",
                    "import warnings\n",
                    "warnings.filterwarnings('ignore')\n",
                    "\n",
                    "# Set random seeds\n",
                    "np.random.seed(42)\n",
                    "torch.manual_seed(42)\n",
                    "\n",
                    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                    "print(f'Using device: {device}')"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["## 2. Load Dataset\n", "\n", f"Loading dataset: **{dataset}**"]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Download and load the dataset\n",
                    "import os\n",
                    "\n",
                    f"# Dataset: {dataset}\n",
                    "# If this is a Kaggle dataset, uncomment and run:\n",
                    f"# !kaggle datasets download -d {dataset}\n",
                    "# !unzip {dataset}.zip -d ./data\n",
                    "\n",
                    "# For now, load your data here:\n",
                    "# df = pd.read_csv('path/to/your/data.csv')\n",
                    "# print(df.head())\n",
                    "# print(f'Dataset shape: {df.shape}')\n",
                    "\n",
                    "print(f'Ready to load dataset: {dataset}')"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["## 3. Data Preprocessing"]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# TODO: Implement preprocessing\n",
                    "# - Handle missing values\n",
                    "# - Normalize/standardize\n",
                    "# - Train/val/test split\n",
                    "\n",
                    "# Example:\n",
                    "# X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["## 4. Model Definition"]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "class BaselineModel(nn.Module):\n",
                    "    def __init__(self, input_dim, num_classes):\n",
                    "        super().__init__()\n",
                    "        self.fc1 = nn.Linear(input_dim, 256)\n",
                    "        self.fc2 = nn.Linear(256, 128)\n",
                    "        self.fc3 = nn.Linear(128, num_classes)\n",
                    "        self.relu = nn.ReLU()\n",
                    "        self.dropout = nn.Dropout(0.3)\n",
                    "    \n",
                    "    def forward(self, x):\n",
                    "        x = self.relu(self.fc1(x))\n",
                    "        x = self.dropout(x)\n",
                    "        x = self.relu(self.fc2(x))\n",
                    "        x = self.dropout(x)\n",
                    "        x = self.fc3(x)\n",
                    "        return x\n",
                    "\n",
                    "# Initialize model\n",
                    "# model = BaselineModel(input_dim=X_train.shape[1], num_classes=num_classes)\n",
                    "# model = model.to(device)"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["## 5. Training Loop"]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "def train_epoch(model, dataloader, criterion, optimizer, device):\n",
                    "    model.train()\n",
                    "    total_loss = 0\n",
                    "    \n",
                    "    for batch_idx, (data, target) in enumerate(dataloader):\n",
                    "        data, target = data.to(device), target.to(device)\n",
                    "        \n",
                    "        optimizer.zero_grad()\n",
                    "        output = model(data)\n",
                    "        loss = criterion(output, target)\n",
                    "        loss.backward()\n",
                    "        optimizer.step()\n",
                    "        \n",
                    "        total_loss += loss.item()\n",
                    "    \n",
                    "    return total_loss / len(dataloader)\n",
                    "\n",
                    "# Training\n",
                    "# criterion = nn.CrossEntropyLoss()\n",
                    "# optimizer = torch.optim.Adam(model.parameters(), lr=0.001)\n",
                    "# \n",
                    "# num_epochs = 10\n",
                    "# for epoch in range(num_epochs):\n",
                    "#     train_loss = train_epoch(model, train_loader, criterion, optimizer, device)\n",
                    "#     print(f'Epoch {epoch+1}/{num_epochs}, Loss: {train_loss:.4f}')"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["## 6. Evaluation"]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "def evaluate(model, dataloader, device):\n",
                    "    model.eval()\n",
                    "    predictions = []\n",
                    "    labels = []\n",
                    "    \n",
                    "    with torch.no_grad():\n",
                    "        for data, target in dataloader:\n",
                    "            data = data.to(device)\n",
                    "            output = model(data)\n",
                    "            pred = output.argmax(dim=1, keepdim=True)\n",
                    "            predictions.extend(pred.cpu().numpy())\n",
                    "            labels.extend(target.numpy())\n",
                    "    \n",
                    "    accuracy = accuracy_score(labels, predictions)\n",
                    "    print(f'Accuracy: {accuracy:.4f}')\n",
                    "    print(classification_report(labels, predictions))\n",
                    "    \n",
                    "    return predictions\n",
                    "\n",
                    "# Evaluate on validation set\n",
                    "# val_predictions = evaluate(model, val_loader, device)"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["## 7. Create Submission"]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Generate predictions for test set\n",
                    "# test_predictions = evaluate(model, test_loader, device)\n",
                    "\n",
                    "# Create submission file\n",
                    "# submission = pd.DataFrame({\n",
                    "#     'id': test_ids,\n",
                    "#     'prediction': test_predictions\n",
                    "# })\n",
                    "# submission.to_csv('submission.csv', index=False)\n",
                    "# print('Submission file created!')\n",
                    "\n",
                    "# Submit to Kaggle\n",
                    "# !kaggle competitions submit -c competition-name -f submission.csv -m 'Baseline submission'"
                ]
            }
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.8.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }
    
    return notebook

# ============ ROUTES ============

@api_router.get("/")
async def root():
    return {"message": "Alexandria API", "version": "4.0.0"}

@api_router.post("/research/step", response_model=StepResponse)
async def research_step(request: StepRequest):
    """Multi-step research journey"""
    try:
        if request.step == 1:
            system_prompt = """You are Alexandria. Provide comprehensive analysis:

## Top 3 Research Papers
| # | Paper | Authors | Contribution | Links |
|---|-------|---------|--------------|-------|
| 1 | [Title] | [Authors] | [Key insight] | [Paper](url) · [Code](url) |

For EACH paper, include working arxiv/github links.

## Full Area Analysis
Provide deep analysis:
- **Current State**: What's the SOTA? What methods dominate?
- **Key Challenges**: What problems remain unsolved?
- **Recent Breakthroughs**: Major advances in last 2 years
- **Performance Benchmarks**: Typical accuracy/metrics achieved

Be comprehensive. Use real data from search."""
            
            response = perplexity_client.chat.completions.create(
                model="sonar-pro",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Research topic: {request.topic}"}
                ],
                extra_body={"search_domain_filter": ["arxiv.org", "github.com", "paperswithcode.com"]}
            )
            
            content = response.choices[0].message.content
            citations = extract_citations(response)
            
            await db.research.insert_one({
                "session_id": request.session_id,
                "step": 1,
                "topic": request.topic,
                "content": content,
                "timestamp": datetime.now(timezone.utc).isoformat()
            })
            
            return StepResponse(step=1, content=content, citations=citations, next_step_available=True)
        
        elif request.step == 2:
            system_prompt = """You are Alexandria. Identify specific research gaps:

## Research Gaps & Opportunities

For each gap (2-3 total):

### Gap 1: **[Specific Gap Title]**
- **Problem**: Detailed problem description
- **Current Limitations**: What methods fail at
- **Proposed Solution**: Novel approach to address it
- **Expected Impact**: Quantitative improvement estimate
- **Difficulty**: Beginner/Intermediate/Advanced

Be specific and actionable."""
            
            response = perplexity_client.chat.completions.create(
                model="sonar-pro",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Find research gaps for: {request.topic}"}
                ],
                extra_body={"search_domain_filter": ["arxiv.org", "paperswithcode.com"]}
            )
            
            content = response.choices[0].message.content
            citations = extract_citations(response)
            
            await db.research.update_one(
                {"session_id": request.session_id, "step": 1},
                {"$set": {"gaps": content}}
            )
            
            return StepResponse(step=2, content=content, citations=citations, next_step_available=True)
        
        elif request.step == 3:
            system_prompt = """You are Alexandria. Find 3-4 dataset options:

## Dataset Options

For EACH dataset:

### Dataset 1: [Name]
- **Source**: Kaggle/HuggingFace/Official
- **Size**: Number of samples, file size
- **Format**: Image/Text/Tabular, file types
- **Difficulty**: Easy/Medium/Hard
- **SOTA Performance**: Best reported score
- **Kaggle Competition**: Yes/No (include link if yes)
- **Access**: Direct download link

Provide working links. Include Kaggle competitions if they exist."""
            
            response = perplexity_client.chat.completions.create(
                model="sonar-pro",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Find datasets for: {request.topic}"}
                ],
                extra_body={"search_domain_filter": ["kaggle.com", "huggingface.co", "paperswithcode.com"]}
            )
            
            content = response.choices[0].message.content
            citations = extract_citations(response)
            
            options = [
                {"id": 1, "name": "Dataset Option 1", "description": "Primary option"},
                {"id": 2, "name": "Dataset Option 2", "description": "Alternative"},
                {"id": 3, "name": "Dataset Option 3", "description": "Backup option"}
            ]
            
            await db.research.update_one(
                {"session_id": request.session_id, "step": 1},
                {"$set": {"datasets": content}}
            )
            
            return StepResponse(step=3, content=content, citations=citations, options=options, next_step_available=False)
        
        elif request.step == 4:
            selected_dataset = request.selected_data.get('dataset_name', 'selected dataset') if request.selected_data else 'selected dataset'
            
            system_prompt = f"""You are Alexandria. Create implementation plan for {selected_dataset}:

## Implementation Checklist

### 1. Environment Setup
```txt
# requirements.txt
torch>=2.0.0
torchvision>=0.15.0
numpy>=1.24.0
pandas>=2.0.0
scikit-learn>=1.3.0
matplotlib>=3.7.0
seaborn>=0.12.0
tqdm>=4.65.0
kaggle>=1.5.16
```

### 2. Data Pipeline
- [ ] Download dataset from Kaggle
- [ ] Data preprocessing
- [ ] Train/val/test split (70/15/15)
- [ ] Data augmentation (if images)

### 3. Model Architecture
- [ ] Baseline model: Simple MLP/CNN
- [ ] Loss function: CrossEntropyLoss
- [ ] Optimizer: Adam (lr=0.001)
- [ ] Training for 10-20 epochs

### 4. Evaluation
- [ ] Accuracy, Precision, Recall, F1
- [ ] Confusion matrix
- [ ] Per-class metrics

### 5. Current SOTA Benchmark
| Metric | Score | Method | Year |
|--------|-------|--------|------|
| Accuracy | 0.XX | [Method] | 2024 |

Be specific."""
            
            response = perplexity_client.chat.completions.create(
                model="sonar-pro",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Implementation plan for {request.topic} using {selected_dataset}"}
                ],
                extra_body={"search_domain_filter": ["github.com", "paperswithcode.com"]}
            )
            
            content = response.choices[0].message.content
            citations = extract_citations(response)
            
            await db.research.update_one(
                {"session_id": request.session_id, "step": 1},
                {"$set": {"implementation": content, "selected_dataset": selected_dataset}}
            )
            
            return StepResponse(step=4, content=content, citations=citations, next_step_available=True)
        
        elif request.step == 5:
            selected_dataset = request.selected_data.get('dataset_name', 'dataset') if request.selected_data else 'dataset'
            
            kaggle_info = ""
            try:
                if 'kaggle' in selected_dataset.lower():
                    kaggle_info = "\n## Kaggle Competition Available\nUse commands below to submit."
            except:
                pass
            
            system_prompt = f"""You are Alexandria. Final setup for shipping:

## Ready to Ship! 🚀

### 1. Kaggle Authentication
```bash
# Setup credentials
export KAGGLE_USERNAME="your_username"
export KAGGLE_KEY="your_api_key"

# Or create ~/.kaggle/kaggle.json
```

### 2. Download Dataset
```bash
kaggle datasets download -d {selected_dataset}
unzip {selected_dataset}.zip
```

### 3. Run Notebook
- Download the generated notebook
- Install requirements: `pip install -r requirements.txt`
- Run all cells
- Train baseline model

### 4. Submit to Kaggle (if competition)
```bash
kaggle competitions submit -c competition-name -f submission.csv -m "Baseline submission from Alexandria"
```

{kaggle_info}

### Next Steps:
1. Click 'Download Notebook' button
2. Download requirements.txt
3. Setup Kaggle credentials
4. Start training!
"""
            
            response = perplexity_client.chat.completions.create(
                model="sonar-pro",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Final setup for {request.topic}"}
                ]
            )
            
            content = response.choices[0].message.content
            citations = extract_citations(response)
            
            await db.research.update_one(
                {"session_id": request.session_id, "step": 1},
                {"$set": {"kaggle_setup": content}}
            )
            
            return StepResponse(step=5, content=content, citations=citations, next_step_available=False)
        
        else:
            raise HTTPException(status_code=400, detail="Invalid step")
            
    except Exception as e:
        logging.error(f"Step {request.step} error: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Step failed: {str(e)}")

@api_router.post("/ship/notebook")
async def download_notebook(request: NotebookRequest):
    """Generate and download Jupyter notebook"""
    try:
        notebook = await generate_notebook_from_research(request.session_id, request.topic, request.dataset_name)
        
        # Convert to JSON string
        notebook_json = json.dumps(notebook, indent=2)
        
        # Create filename
        safe_topic = request.topic.replace(' ', '_').replace('/', '_')[:50]
        filename = f"alexandria_{safe_topic}.ipynb"
        
        # Return as downloadable file
        return StreamingResponse(
            io.BytesIO(notebook_json.encode()),
            media_type="application/x-ipynb+json",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )
        
    except Exception as e:
        logging.error(f"Notebook generation error: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@api_router.post("/ship/push-to-kaggle")
async def push_to_kaggle(request: NotebookRequest):
    """Generate notebook with research data and push to Kaggle, return shareable link"""
    try:
        # Generate notebook with ALL research data
        notebook = await generate_notebook_from_research(request.session_id, request.topic, request.dataset_name)
        
        # Create safe kernel slug
        safe_topic = request.topic.lower().replace(' ', '-').replace('_', '-')[:50]
        safe_topic = ''.join(c for c in safe_topic if c.isalnum() or c == '-')
        
        # IMPORTANT: Kaggle API often blocks NEW kernel creation (403 Forbidden)
        # Instead, we'll update an existing kernel or provide manual upload instructions
        
        # Try to get user's existing kernels
        try:
            result = run_kaggle_command(['kaggle', 'kernels', 'list', '--mine'])
            has_kernels = 'evanoleary/' in result
        except:
            has_kernels = False
        
        # Always create a new kernel with matching title and slug
        kernel_slug = f"alexandria-{safe_topic}"
        kernel_id = f"{kaggle_username}/{kernel_slug}"
        
        # Create title that matches the slug (Kaggle requirement)
        # Title must generate the same slug when converted
        kernel_title = f"Alexandria {request.topic.title()}"[:80]
        
        # Create temp directory for kernel
        with tempfile.TemporaryDirectory() as temp_dir:
            notebook_path = os.path.join(temp_dir, "notebook.ipynb")
            metadata_path = os.path.join(temp_dir, "kernel-metadata.json")
            
            # Write notebook file
            with open(notebook_path, 'w') as f:
                json.dump(notebook, f, indent=2)
            
            # Create kernel metadata
            metadata = {
                "id": kernel_id,
                "title": kernel_title,  # Must match slug format
                "code_file": "notebook.ipynb",
                "language": "python",
                "kernel_type": "notebook",
                "is_private": False,
                "enable_gpu": True,
                "enable_internet": True,
                "dataset_sources": [],
                "competition_sources": [],
                "kernel_sources": []
            }
            
            # Only add dataset if it has proper format
            if request.dataset_name and '/' in request.dataset_name:
                metadata["dataset_sources"].append(request.dataset_name)
            
            # Write metadata file
            with open(metadata_path, 'w') as f:
                json.dump(metadata, f, indent=2)
            
            # Try to push to Kaggle
            logging.info(f"Attempting to push/update kernel: {kernel_id}")
            
            try:
                result = run_kaggle_command(['kaggle', 'kernels', 'push', '-p', temp_dir])
                logging.info(f"Kaggle CLI output: {result}")
                
                # Check for specific errors
                if "403" in result or "Forbidden" in result:
                    # 403 Forbidden - account verification or permissions issue
                    raise HTTPException(
                        status_code=403,
                        detail="Kaggle API access denied. Your account may need phone verification or additional permissions. Please: 1) Go to kaggle.com/settings 2) Verify your phone number 3) Check API token permissions"
                    )
                elif "error" in result.lower() and "successfully" not in result.lower():
                    raise HTTPException(status_code=500, detail=f"Kaggle API error: {result}")
                
                # Success! Generate link
                kaggle_link = f"https://www.kaggle.com/code/{kernel_id}"
                
                return {
                    "status": "success",
                    "message": "Notebook pushed to Kaggle successfully!",
                    "kaggle_link": kaggle_link,
                    "kernel_slug": kernel_slug,
                    "username": kaggle_username
                }
                
            except subprocess.TimeoutExpired:
                raise HTTPException(status_code=504, detail="Kaggle API timeout - please try again")
            
    except HTTPException:
        raise
    except Exception as e:
        logging.error(f"Kaggle push error: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to push to Kaggle: {str(e)}")

@api_router.get("/ship/requirements")
async def download_requirements():
    """Download requirements.txt"""
    requirements = """torch>=2.0.0
torchvision>=0.15.0
numpy>=1.24.0
pandas>=2.0.0
scikit-learn>=1.3.0
matplotlib>=3.7.0
seaborn>=0.12.0
tqdm>=4.65.0
kaggle>=1.5.16
jupyter>=1.0.0
"""
    
    return StreamingResponse(
        io.BytesIO(requirements.encode()),
        media_type="text/plain",
        headers={"Content-Disposition": "attachment; filename=requirements.txt"}
    )

@api_router.post("/ship/setup-kaggle")
async def setup_kaggle_credentials():
    """Setup Kaggle credentials automatically"""
    try:
        # Create kaggle config
        kaggle_config = {
            "username": kaggle_username,
            "key": kaggle_key
        }
        
        # Return config as JSON
        return {
            "status": "success",
            "message": "Kaggle credentials configured",
            "config": kaggle_config,
            "instructions": "Credentials are already set up on the server"
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@api_router.post("/ship/download-dataset")
async def download_dataset(dataset_name: str):
    """Download dataset from Kaggle"""
    try:
        logging.info(f"Downloading dataset: {dataset_name}")
        
        # Download using kaggle CLI
        output = run_kaggle_command([
            'kaggle', 'datasets', 'download', '-d', dataset_name, '-p', '/tmp'
        ])
        
        return {
            "status": "success",
            "message": f"Dataset {dataset_name} downloaded to /tmp",
            "output": output,
            "download_path": f"/tmp/{dataset_name}.zip"
        }
    except Exception as e:
        logging.error(f"Dataset download error: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to download: {str(e)}")

@api_router.post("/ship/install-requirements")
async def install_requirements():
    """Install Python requirements"""
    try:
        # Run pip install
        result = subprocess.run(
            ['pip', 'install', '-q', 'torch', 'torchvision', 'numpy', 'pandas', 
             'scikit-learn', 'matplotlib', 'seaborn', 'tqdm', 'kaggle', 'jupyter'],
            capture_output=True,
            text=True,
            timeout=300
        )
        
        return {
            "status": "success",
            "message": "Requirements installed successfully",
            "output": result.stdout,
            "packages": ['torch', 'torchvision', 'numpy', 'pandas', 'scikit-learn', 
                        'matplotlib', 'seaborn', 'tqdm', 'kaggle', 'jupyter']
        }
    except Exception as e:
        logging.error(f"Installation error: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@api_router.post("/ship/run-notebook")
async def run_notebook(notebook_path: str):
    """Execute Jupyter notebook"""
    try:
        # Convert and execute notebook
        result = subprocess.run(
            ['jupyter', 'nbconvert', '--to', 'notebook', '--execute', 
             notebook_path, '--output', 'executed_notebook.ipynb'],
            capture_output=True,
            text=True,
            timeout=600
        )
        
        return {
            "status": "success",
            "message": "Notebook executed successfully",
            "output_path": "executed_notebook.ipynb",
            "logs": result.stdout
        }
    except Exception as e:
        logging.error(f"Notebook execution error: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

@api_router.post("/ship/submit-kaggle")
async def submit_to_kaggle(competition: str, file_path: str, message: str = "Submission from Alexandria"):
    """Submit to Kaggle competition"""
    try:
        output = run_kaggle_command([
            'kaggle', 'competitions', 'submit', 
            '-c', competition, 
            '-f', file_path, 
            '-m', message
        ])
        
        return {
            "status": "success",
            "message": "Submitted to Kaggle",
            "competition": competition,
            "output": output
        }
    except Exception as e:
        logging.error(f"Submission error: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

app.include_router(api_router)

app.add_middleware(
    CORSMiddleware,
    allow_credentials=True,
    allow_origins=os.environ.get('CORS_ORIGINS', '*').split(','),
    allow_methods=["*"],
    allow_headers=["*"],
)

logging.basicConfig(level=logging.INFO)

@app.on_event("shutdown")
async def shutdown_db_client():
    client.close()