import React, { useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import axios from 'axios';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { ArrowLeft, Download, FileText, Code, Rocket, ExternalLink, CheckCircle2, Copy } from 'lucide-react';
import { toast } from 'sonner';

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const API = `${BACKEND_URL}/api`;

export default function ShipPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const { topic, dataset, sessionId } = location.state || {};
  const [notebookPreview, setNotebookPreview] = useState('');

  useEffect(() => {
    if (!topic) {
      navigate('/');
      return;
    }
    loadNotebookPreview();
  }, [topic]);

  const loadNotebookPreview = () => {
    // Generate preview of notebook code
    const preview = `# ${topic}
# Dataset: ${dataset}
# Generated by Alexandria

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

import warnings
warnings.filterwarnings('ignore')

# Set random seeds
np.random.seed(42)
torch.manual_seed(42)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')

# Load Dataset
# kaggle datasets download -d ${dataset}

# Model Definition
class BaselineModel(nn.Module):
    def __init__(self, input_dim, num_classes):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, 256)
        self.fc2 = nn.Linear(256, 128)
        self.fc3 = nn.Linear(128, num_classes)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.3)
    
    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.relu(self.fc2(x))
        x = self.dropout(x)
        x = self.fc3(x)
        return x

# Training Loop
def train_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    total_loss = 0
    
    for batch_idx, (data, target) in enumerate(dataloader):
        data, target = data.to(device), target.to(device)
        
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
    
    return total_loss / len(dataloader)

# Evaluation
def evaluate(model, dataloader, device):
    model.eval()
    predictions = []
    labels = []
    
    with torch.no_grad():
        for data, target in dataloader:
            data = data.to(device)
            output = model(data)
            pred = output.argmax(dim=1, keepdim=True)
            predictions.extend(pred.cpu().numpy())
            labels.extend(target.numpy())
    
    accuracy = accuracy_score(labels, predictions)
    print(f'Accuracy: {accuracy:.4f}')
    print(classification_report(labels, predictions))
    
    return predictions

# Create submission
# submission = pd.DataFrame({'id': test_ids, 'prediction': test_predictions})
# submission.to_csv('submission.csv', index=False)
# !kaggle competitions submit -c competition-name -f submission.csv -m 'Baseline from Alexandria'`;

    setNotebookPreview(preview);
  };

  const handleDownloadNotebook = async () => {
    try {
      const response = await axios.post(
        `${API}/ship/notebook`,
        { session_id: sessionId, topic: topic, dataset_name: dataset },
        { responseType: 'blob' }
      );
      
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `alexandria_${topic.replace(/\s+/g, '_')}.ipynb`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      
      toast.success('Notebook downloaded!');
    } catch (error) {
      toast.error('Failed to download notebook');
    }
  };

  const handleDownloadRequirements = async () => {
    try {
      const response = await axios.get(`${API}/ship/requirements`, { responseType: 'blob' });
      
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', 'requirements.txt');
      document.body.appendChild(link);
      link.click();
      link.remove();
      
      toast.success('requirements.txt downloaded!');
    } catch (error) {
      toast.error('Failed to download requirements');
    }
  };

  const handleCopyCode = () => {
    navigator.clipboard.writeText(notebookPreview);
    toast.success('Code copied to clipboard!');
  };

  const kaggleSetupSteps = [
    {
      title: '1. Setup Kaggle Credentials',
      code: `# Create ~/.kaggle/kaggle.json
{
  "username": "your_username",
  "key": "your_api_key"
}`
    },
    {
      title: '2. Download Dataset',
      code: `kaggle datasets download -d ${dataset || 'dataset-name'}
unzip ${dataset || 'dataset-name'}.zip`
    },
    {
      title: '3. Install Requirements',
      code: `pip install -r requirements.txt`
    },
    {
      title: '4. Run Notebook',
      code: `jupyter notebook alexandria_${topic?.replace(/\s+/g, '_')}.ipynb`
    },
    {
      title: '5. Submit to Kaggle',
      code: `kaggle competitions submit -c competition-name -f submission.csv -m "Alexandria baseline"`
    }
  ];

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <Button 
            variant="ghost" 
            size="sm"
            onClick={() => navigate(-1)}
            data-testid="back-btn"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back
          </Button>
          <img src="/alexandria-logo.png" alt="Alexandria" className="h-8" />
          <div className="w-20" /> {/* Spacer for centering */}
        </div>
      </header>

      {/* Hero Section */}
      <div className="bg-gradient-to-r from-green-600 to-emerald-600 text-white py-12">
        <div className="max-w-7xl mx-auto px-6 text-center">
          <div className="flex items-center justify-center gap-3 mb-4">
            <Rocket className="w-12 h-12" />
            <h1 className="text-4xl font-bold">Ready to Ship!</h1>
          </div>
          <p className="text-xl text-green-100 mb-6">{topic}</p>
          <Badge className="bg-white text-green-700 px-6 py-2 text-base">
            <CheckCircle2 className="w-5 h-5 mr-2" />
            Dataset: {dataset || 'Selected'}
          </Badge>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-7xl mx-auto px-6 py-8">
        <div className="grid lg:grid-cols-3 gap-6">
          {/* Left Column - Downloads */}
          <div className="lg:col-span-1 space-y-4">
            <Card className="p-6">
              <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
                <Download className="w-5 h-5" />
                Download Files
              </h2>
              
              <div className="space-y-3">
                <Button
                  onClick={handleDownloadNotebook}
                  className="w-full h-16 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700"
                  data-testid="download-notebook-btn"
                >
                  <div className="flex flex-col items-center gap-1">
                    <FileText className="w-6 h-6" />
                    <span className="font-semibold">Jupyter Notebook</span>
                  </div>
                </Button>
                
                <Button
                  onClick={handleDownloadRequirements}
                  variant="outline"
                  className="w-full h-16 border-2"
                  data-testid="download-requirements-btn"
                >
                  <div className="flex flex-col items-center gap-1">
                    <Code className="w-6 h-6" />
                    <span className="font-semibold">requirements.txt</span>
                  </div>
                </Button>
              </div>
            </Card>

            {/* Quick Links */}
            <Card className="p-6">
              <h3 className="text-lg font-semibold mb-3">Quick Links</h3>
              <div className="space-y-2">
                <a
                  href="https://www.kaggle.com/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 text-blue-600 hover:underline text-sm"
                >
                  <ExternalLink className="w-4 h-4" />
                  Kaggle Platform
                </a>
                <a
                  href="https://www.kaggle.com/docs/api"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 text-blue-600 hover:underline text-sm"
                >
                  <ExternalLink className="w-4 h-4" />
                  Kaggle API Docs
                </a>
                <a
                  href="https://pytorch.org/docs/stable/index.html"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 text-blue-600 hover:underline text-sm"
                >
                  <ExternalLink className="w-4 h-4" />
                  PyTorch Documentation
                </a>
              </div>
            </Card>
          </div>

          {/* Right Column - Content */}
          <div className="lg:col-span-2">
            <Card className="p-6">
              <Tabs defaultValue="notebook" className="w-full">
                <TabsList className="grid w-full grid-cols-2">
                  <TabsTrigger value="notebook">Notebook Preview</TabsTrigger>
                  <TabsTrigger value="setup">Setup Guide</TabsTrigger>
                </TabsList>
                
                <TabsContent value="notebook" className="mt-6">
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="text-lg font-semibold">Code Preview</h3>
                    <Button
                      onClick={handleCopyCode}
                      variant="outline"
                      size="sm"
                    >
                      <Copy className="w-4 h-4 mr-2" />
                      Copy Code
                    </Button>
                  </div>
                  
                  <pre className="bg-gray-900 text-gray-100 p-6 rounded-lg overflow-x-auto text-sm font-mono max-h-[600px] overflow-y-auto">
                    {notebookPreview}
                  </pre>
                </TabsContent>
                
                <TabsContent value="setup" className="mt-6">
                  <h3 className="text-lg font-semibold mb-4">Setup Instructions</h3>
                  
                  <div className="space-y-6">
                    {kaggleSetupSteps.map((step, idx) => (
                      <div key={idx} className="border-l-4 border-blue-500 pl-4">
                        <h4 className="font-semibold text-gray-900 mb-2">{step.title}</h4>
                        <pre className="bg-gray-100 p-3 rounded text-sm font-mono overflow-x-auto">
                          {step.code}
                        </pre>
                      </div>
                    ))}
                  </div>
                  
                  <div className="mt-8 p-4 bg-green-50 border border-green-200 rounded-lg">
                    <h4 className="font-semibold text-green-900 mb-2 flex items-center gap-2">
                      <CheckCircle2 className="w-5 h-5" />
                      You're All Set!
                    </h4>
                    <p className="text-green-800 text-sm">
                      Download the notebook and requirements.txt, follow the setup steps, and start training your model!
                    </p>
                  </div>
                </TabsContent>
              </Tabs>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}